    /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.view;

import com.DAO.CategoriaDAO;
import com.DAO.PrioridadDAO;
import com.DAO.TareaDAO;
import com.DAO.UsuarioDAO;
import com.models.Categoria;
import com.models.Prioridad;
import com.models.Tarea;
import com.models.Usuario;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import java.util.logging.Logger;
import java.util.logging.Level;

/**
 *
 * @author Davestriid
 */
public class AgregarTarea extends javax.swing.JFrame {

    /**
     * Creates new form Agregar_tarea
     */
    
    private Tarea editarTarea = null; 
   
    public AgregarTarea() {
        initComponents();
        txtAgregarTituloTarea.requestFocus();
        cargarCategorias();
        cargarPrioridades();
        cargarUsuarios();
    }
    
    public AgregarTarea(Tarea tarea) {
        initComponents();
        this.editarTarea = tarea;

        cargarCategorias();
        cargarPrioridades();
        cargarUsuarios();

        // precargar los campos con los datos de la tarea
        if (tarea != null) {
            txtAgregarTituloTarea.setText(tarea.getTitulo());
            txtAgregarDescripcionTarea.setText(tarea.getDescripcion());
            txtAgregarComentarioTarea.setText(""); 
            dateAgregarFechaEntregaTarea.setDate(tarea.getFechaVencimiento());
            boxAgregarCategoriaTarea.setSelectedItem(tarea.getIdCategoria().getNombreCategoria());
            boxAgregarPrioridadTarea.setSelectedItem(tarea.getIdPrioridad().getNombrePrioridad());
            boxAgregarUsuarioTarea.setSelectedItem(tarea.getIdUsuario().getNombre());
        }
    }

    private void cargarCategorias() {
        CategoriaDAO categoriaDAO = new CategoriaDAO();
        try {
            List<Categoria> categorias = categoriaDAO.buscarTodasLasCategorias();
            boxAgregarCategoriaTarea.removeAllItems();
            boxAgregarCategoriaTarea.addItem("Seleccionar una categoría");
            for (Categoria c : categorias) {
                boxAgregarCategoriaTarea.addItem(c.getNombreCategoria()); 
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar categorías: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(AgregarTarea.class.getName()).log(Level.SEVERE, "Error al cargar categorías", e);
        }
    }

    private void cargarPrioridades() {
        PrioridadDAO prioridadDAO = new PrioridadDAO();
        try {
            List<Prioridad> prioridades = prioridadDAO.buscarTodasLasPrioridades();
            boxAgregarPrioridadTarea.removeAllItems();
            boxAgregarPrioridadTarea.addItem("Seleccionar una prioridad");
            for (Prioridad p : prioridades) {
                boxAgregarPrioridadTarea.addItem(p.getNombrePrioridad());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar prioridades: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(AgregarTarea.class.getName()).log(Level.SEVERE, "Error al cargar prioridades", e);
        }
    }

    private void cargarUsuarios() {
        UsuarioDAO usuarioDAO = new UsuarioDAO();
        try {
            List<Usuario> usuarios = usuarioDAO.buscarTodosLosUsuarios();
            boxAgregarUsuarioTarea.addItem("Seleccione un usuario");
            for (Usuario u : usuarios) {
                boxAgregarUsuarioTarea.addItem(u.getNombre());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar usuarios: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(AgregarTarea.class.getName()).log(Level.SEVERE, "Error al cargar usuarios", e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtAgregarTituloTarea = new javax.swing.JTextField();
        txtAgregarDescripcionTarea = new javax.swing.JTextField();
        txtAgregarComentarioTarea = new javax.swing.JTextField();
        boxAgregarPrioridadTarea = new javax.swing.JComboBox<>();
        dateAgregarFechaEntregaTarea = new com.toedter.calendar.JDateChooser();
        dateAgregarRecordatorioTarea = new com.toedter.calendar.JDateChooser();
        btnGuardarTarea = new javax.swing.JButton();
        btnCancelarTarea = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        boxAgregarUsuarioTarea = new javax.swing.JComboBox<>();
        boxAgregarCategoriaTarea = new javax.swing.JComboBox<>();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel2.setText("Agregar tarea");

        jLabel1.setText("Título");

        jLabel3.setText("Descripción");

        jLabel4.setText("Usuario");

        jLabel5.setText("Prioridad");

        jLabel6.setText("Fecha de entrega");

        jLabel7.setText("Recordatorio");

        jLabel8.setText("Comentarios");

        txtAgregarTituloTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgregarTituloTareaActionPerformed(evt);
            }
        });

        btnGuardarTarea.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        btnGuardarTarea.setText("GUARDAR");
        btnGuardarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarTareaActionPerformed(evt);
            }
        });

        btnCancelarTarea.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        btnCancelarTarea.setText("Cancelar");
        btnCancelarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarTareaActionPerformed(evt);
            }
        });

        jLabel9.setText("Categorías");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2)
                                .addComponent(boxAgregarUsuarioTarea, 0, 300, Short.MAX_VALUE)
                                .addComponent(txtAgregarTituloTarea)
                                .addComponent(txtAgregarDescripcionTarea))
                            .addComponent(boxAgregarCategoriaTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(dateAgregarRecordatorioTarea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAgregarComentarioTarea)
                    .addComponent(boxAgregarPrioridadTarea, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateAgregarFechaEntregaTarea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(btnGuardarTarea)
                .addGap(55, 55, 55)
                .addComponent(btnCancelarTarea)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtAgregarTituloTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(boxAgregarUsuarioTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAgregarDescripcionTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxAgregarCategoriaTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boxAgregarPrioridadTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addComponent(dateAgregarFechaEntregaTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateAgregarRecordatorioTarea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAgregarComentarioTarea, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarTarea)
                    .addComponent(btnCancelarTarea))
                .addGap(12, 12, 12))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtAgregarTituloTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgregarTituloTareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgregarTituloTareaActionPerformed

    private void btnCancelarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarTareaActionPerformed
        // TODO add your handling code here:
        VistaAdministrador tareasList = new VistaAdministrador();
        tareasList.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarTareaActionPerformed

    private void btnGuardarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarTareaActionPerformed
        // TODO add your handling code here:

        try {
            String titulo = txtAgregarTituloTarea.getText().trim();
            String descripcion = txtAgregarDescripcionTarea.getText().trim();
            Date fechaVencimiento = dateAgregarFechaEntregaTarea.getDate();
            String nombreCategoria = (String) boxAgregarCategoriaTarea.getSelectedItem();
            String nombrePrioridad = (String) boxAgregarPrioridadTarea.getSelectedItem();
            String nombreUsuario = (String) boxAgregarUsuarioTarea.getSelectedItem();
            
            if (titulo.isEmpty() || descripcion.isEmpty() || fechaVencimiento == null
                    || nombreCategoria == null || nombrePrioridad == null || nombreUsuario == null
                    || nombreCategoria.equals("Seleccione una categoría")
                    || nombrePrioridad.equals("Seleccionar una prioridad")
                    || nombreUsuario.equals("Seleccione un usuario")) {
                JOptionPane.showMessageDialog(this, "Por favor completa todos los campos.");
                return;
            }

            // Buscar los objetos completos a partir del nombre
            
            Categoria categoria = new CategoriaDAO().buscarPorNombre(nombreCategoria);
            Prioridad prioridad = new PrioridadDAO().buscarPorNombre(nombrePrioridad);
            Usuario usuario = new UsuarioDAO().buscarPorNombre(nombreUsuario);


            if (categoria == null || prioridad == null || usuario == null) {
                JOptionPane.showMessageDialog(this, "No se pudo obtener los datos seleccionados.");
                return;
            }

            // Si estás editando una tarea existente
            if (editarTarea != null) {
                editarTarea.setTitulo(titulo);
                editarTarea.setDescripcion(descripcion);
                editarTarea.setFechaVencimiento(fechaVencimiento);
                editarTarea.setIdCategoria(categoria);
                editarTarea.setIdPrioridad(prioridad);
                editarTarea.setIdUsuario(usuario);
                new TareaDAO().actualizarTarea(editarTarea);
                JOptionPane.showMessageDialog(this, "Tarea actualizada exitosamente.");
            } else {
                // Nueva tarea
                Tarea nuevaTarea = new Tarea();
                nuevaTarea.setTitulo(titulo);
                nuevaTarea.setDescripcion(descripcion);
                nuevaTarea.setFechaVencimiento(fechaVencimiento);
                nuevaTarea.setEstado("pendiente");
                nuevaTarea.setIdCategoria(categoria);
                nuevaTarea.setIdPrioridad(prioridad);
                nuevaTarea.setIdUsuario(usuario);
                new TareaDAO().guardarTarea(nuevaTarea);
                JOptionPane.showMessageDialog(this, "Tarea guardada exitosamente.");
            }

            new VistaAdministrador().setVisible(true);
            this.dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al guardar/actualizar tarea: " + e);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnGuardarTareaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarTarea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxAgregarCategoriaTarea;
    private javax.swing.JComboBox<String> boxAgregarPrioridadTarea;
    private javax.swing.JComboBox<String> boxAgregarUsuarioTarea;
    private javax.swing.JButton btnCancelarTarea;
    private javax.swing.JButton btnGuardarTarea;
    private com.toedter.calendar.JDateChooser dateAgregarFechaEntregaTarea;
    private com.toedter.calendar.JDateChooser dateAgregarRecordatorioTarea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtAgregarComentarioTarea;
    private javax.swing.JTextField txtAgregarDescripcionTarea;
    private javax.swing.JTextField txtAgregarTituloTarea;
    // End of variables declaration//GEN-END:variables
}
