/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.view;

import com.DAO.TareaDAO;
import com.models.Tarea;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *  
 * @author Davestriid
 */
public class ListadoDeTareas extends javax.swing.JFrame {

    /**
     * Creates new form Listado_de_tareas
     */
    
    
    private List<Tarea> listaDeTareas;

    public ListadoDeTareas() {
        initComponents();
        cargarListaDeTareas();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnEliminarTarea = new javax.swing.JButton();
        btnTerminarTarea = new javax.swing.JButton();
        btnFormularioTarea = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaTareas = new javax.swing.JTable();
        btnVerCategorias = new javax.swing.JButton();
        btnVerComentarios = new javax.swing.JButton();
        btnVerUsuarios = new javax.swing.JButton();
        btnEditarTarea = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel1.setText("Listado de tareas");

        btnEliminarTarea.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        btnEliminarTarea.setText("Eliminar");
        btnEliminarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTareaActionPerformed(evt);
            }
        });

        btnTerminarTarea.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        btnTerminarTarea.setText("Terminar");
        btnTerminarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarTareaActionPerformed(evt);
            }
        });

        btnFormularioTarea.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        btnFormularioTarea.setText("Agregar");
        btnFormularioTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormularioTareaActionPerformed(evt);
            }
        });

        tablaTareas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaTareas);

        btnVerCategorias.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        btnVerCategorias.setText("CATEGORIAS");
        btnVerCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerCategoriasActionPerformed(evt);
            }
        });

        btnVerComentarios.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        btnVerComentarios.setText("COMENTARIOS");
        btnVerComentarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerComentariosActionPerformed(evt);
            }
        });

        btnVerUsuarios.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        btnVerUsuarios.setText("USUARIOS");
        btnVerUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerUsuariosActionPerformed(evt);
            }
        });

        btnEditarTarea.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        btnEditarTarea.setText("EDITAR");
        btnEditarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarTareaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(btnVerComentarios)
                            .addComponent(btnVerCategorias)
                            .addComponent(btnVerUsuarios)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(238, 238, 238)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(btnFormularioTarea)
                                .addGap(65, 65, 65)
                                .addComponent(btnEditarTarea)
                                .addGap(65, 65, 65)
                                .addComponent(btnEliminarTarea)
                                .addGap(65, 65, 65)
                                .addComponent(btnTerminarTarea)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnVerUsuarios)
                        .addGap(18, 18, 18)
                        .addComponent(btnVerCategorias)
                        .addGap(18, 18, 18)
                        .addComponent(btnVerComentarios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTerminarTarea)
                    .addComponent(btnEliminarTarea)
                    .addComponent(btnEditarTarea)
                    .addComponent(btnFormularioTarea))
                .addGap(27, 27, 27))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void cargarListaDeTareas() {
        TareaDAO dao = new TareaDAO();
        this.listaDeTareas = dao.obtenerTodasLasTareas(); 

        String[] columnas = {"ID", "Título", "Descripción", "Fecha Vencimiento", "Estado"};
        DefaultTableModel modelo = new DefaultTableModel(null, columnas);

        for (Tarea t : listaDeTareas) {
            Object[] fila = {
                t.getIdTarea(), 
                t.getTitulo(),
                t.getDescripcion(),
                t.getFechaVencimiento(),
                t.getEstado()
            };
            modelo.addRow(fila);
        }
        
        
        // para actualizar los datos de la tabla
        tablaTareas.setModel(modelo);
        
        //para ocultar visualmente el id
        tablaTareas.getColumnModel().getColumn(0).setMinWidth(0);
        tablaTareas.getColumnModel().getColumn(0).setMaxWidth(0);
        tablaTareas.getColumnModel().getColumn(0).setWidth(0);
    }
    
    private void btnFormularioTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormularioTareaActionPerformed
        // TODO add your handling code here:
        AgregarTarea aggTarea = new AgregarTarea(); 
        aggTarea.setVisible(true);
        this.dispose();
    
    }//GEN-LAST:event_btnFormularioTareaActionPerformed

    private void btnVerUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerUsuariosActionPerformed
        // TODO add your handling code here:
        AgregarUsuario aggUsuario = new AgregarUsuario(); 
        aggUsuario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVerUsuariosActionPerformed

    private void btnVerCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCategoriasActionPerformed
        // TODO add your handling code here:
        
        AgregarCategoria aggcat = new AgregarCategoria(); 
        aggcat.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVerCategoriasActionPerformed

    private void btnVerComentariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerComentariosActionPerformed
        // TODO add your handling code here:
        
        AgregarComentario aggcom = new AgregarComentario(); 
        aggcom.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVerComentariosActionPerformed

    private void btnEditarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarTareaActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = tablaTareas.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Por favor selecciona una tarea para editar.");
            return;
        }

        // Obtener el ID desde la primera columna
        int idTarea = Integer.parseInt(tablaTareas.getValueAt(filaSeleccionada, 0).toString());

        // Buscar la tarea desde la base de datos
        TareaDAO dao = new TareaDAO();
        Tarea tareaEncontrada = dao.buscarPorId(idTarea);

        // Si la encuentra, abre el formulario con los datos
        if (tareaEncontrada != null) {
            AgregarTarea editarForm = new AgregarTarea(tareaEncontrada);
            editarForm.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró la tarea.");
        }
    }//GEN-LAST:event_btnEditarTareaActionPerformed

    private void btnEliminarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTareaActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = tablaTareas.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona una tarea para eliminar.");
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(
                this,
                "¿Estás seguro de que deseas eliminar esta tarea?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION
        );

        if (confirmacion == JOptionPane.YES_OPTION) {
            // Obtener ID oculto de la tarea desde la columna 0
            int idTarea = (int) tablaTareas.getValueAt(filaSeleccionada, 0);

            // Eliminar de la base de datos
            TareaDAO dao = new TareaDAO();
            Tarea tarea = dao.obtenerTareaPorId(idTarea);
            dao.eliminarTarea(tarea);

            // Recargar visualmente la tabla
            cargarListaDeTareas();

            JOptionPane.showMessageDialog(this, "Tarea eliminada correctamente.");
        }
    }//GEN-LAST:event_btnEliminarTareaActionPerformed

    private void btnTerminarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarTareaActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_btnTerminarTareaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListadoDeTareas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListadoDeTareas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListadoDeTareas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListadoDeTareas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListadoDeTareas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarTarea;
    private javax.swing.JButton btnEliminarTarea;
    private javax.swing.JButton btnFormularioTarea;
    private javax.swing.JButton btnTerminarTarea;
    private javax.swing.JButton btnVerCategorias;
    private javax.swing.JButton btnVerComentarios;
    private javax.swing.JButton btnVerUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaTareas;
    // End of variables declaration//GEN-END:variables
}
