/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.view;

import com.DAO.TareaDAO;
import com.models.Tarea;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Davestriid
 */
public class VistaUsuario extends javax.swing.JFrame {

    /**
     * Creates new form VistaUsuario
     */
    
    private List<Tarea> listaDeTareas;

    public VistaUsuario() {
        initComponents();
        cargarListaDeTareas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnEliminarTareaUsuario = new javax.swing.JButton();
        btnFormularioTareaUsuario = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaTareasUsuario = new javax.swing.JTable();
        btnEditarTareaUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel1.setText("Listado de tareas");

        btnEliminarTareaUsuario.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        btnEliminarTareaUsuario.setText("Eliminar");
        btnEliminarTareaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTareaUsuarioActionPerformed(evt);
            }
        });

        btnFormularioTareaUsuario.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        btnFormularioTareaUsuario.setText("Agregar");
        btnFormularioTareaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormularioTareaUsuarioActionPerformed(evt);
            }
        });

        tablaTareasUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaTareasUsuario);

        btnEditarTareaUsuario.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        btnEditarTareaUsuario.setText("EDITAR");
        btnEditarTareaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarTareaUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 642, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(214, 214, 214)
                                    .addComponent(jLabel1))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(115, 115, 115)
                                    .addComponent(btnFormularioTareaUsuario)
                                    .addGap(65, 65, 65)
                                    .addComponent(btnEditarTareaUsuario)
                                    .addGap(65, 65, 65)
                                    .addComponent(btnEliminarTareaUsuario)))
                            .addGap(124, 124, 124)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnEliminarTareaUsuario)
                        .addComponent(btnEditarTareaUsuario)
                        .addComponent(btnFormularioTareaUsuario))
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    private void cargarListaDeTareas() {
        TareaDAO dao = new TareaDAO();
        this.listaDeTareas = dao.obtenerTodasLasTareas(); 

        String[] columnas = {"ID", "Título", "Usuario","Descripción", "Fecha Vencimiento", "Estado", "Comentarios"};
        DefaultTableModel modelo = new DefaultTableModel(null, columnas);

        for (Tarea t : listaDeTareas) {
            Object[] fila = {
                t.getIdTarea(), 
                t.getTitulo(),
                t.getIdUsuario(),
                t.getDescripcion(),
                t.getFechaVencimiento(),
                t.getEstado(),
                t.getComentariosList()
            };
            modelo.addRow(fila);
        }
        
        
        // para actualizar los datos de la tabla
        tablaTareasUsuario.setModel(modelo);
        
        //para ocultar visualmente el id
        tablaTareasUsuario.getColumnModel().getColumn(0).setMinWidth(0);
        tablaTareasUsuario.getColumnModel().getColumn(0).setMaxWidth(0);
        tablaTareasUsuario.getColumnModel().getColumn(0).setWidth(0);
    }
    
    private void btnEliminarTareaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTareaUsuarioActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = tablaTareasUsuario.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona una tarea para eliminar.");
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(
            this,
            "¿Estás seguro de que deseas eliminar esta tarea?",
            "Confirmar eliminación",
            JOptionPane.YES_NO_OPTION
        );

        if (confirmacion == JOptionPane.YES_OPTION) {
            // Obtener ID oculto de la tarea desde la columna 0
            int idTarea = (int) tablaTareasUsuario.getValueAt(filaSeleccionada, 0);

            // Eliminar de la base de datos
            TareaDAO dao = new TareaDAO();
            Tarea tarea = dao.obtenerTareaPorId(idTarea);
            dao.eliminarTarea(tarea);

            // Recargar visualmente la tabla
            cargarListaDeTareas();

            JOptionPane.showMessageDialog(this, "Tarea eliminada correctamente.");
        }
    }//GEN-LAST:event_btnEliminarTareaUsuarioActionPerformed

    private void btnFormularioTareaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormularioTareaUsuarioActionPerformed
        // TODO add your handling code here:
        AgregarTarea aggTarea = new AgregarTarea();
        aggTarea.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnFormularioTareaUsuarioActionPerformed

    private void btnEditarTareaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarTareaUsuarioActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = tablaTareasUsuario.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Por favor selecciona una tarea para editar.");
            return;
        }

        // Obtener el ID desde la primera columna
        int idTarea = Integer.parseInt(tablaTareasUsuario.getValueAt(filaSeleccionada, 0).toString());

        // Buscar la tarea desde la base de datos
        TareaDAO dao = new TareaDAO();
        Tarea tareaEncontrada = dao.buscarPorId(idTarea);

        // Si la encuentra, abre el formulario con los datos
        if (tareaEncontrada != null) {
            AgregarTarea editarForm = new AgregarTarea(tareaEncontrada);
            editarForm.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró la tarea.");
        }
    }//GEN-LAST:event_btnEditarTareaUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarTareaUsuario;
    private javax.swing.JButton btnEliminarTareaUsuario;
    private javax.swing.JButton btnFormularioTareaUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaTareasUsuario;
    // End of variables declaration//GEN-END:variables
}
